# Approve PRs with "pr/auto-approve". mergify takes care of the actual merge.

name: auto-approve
on:
  pull_request_target:
    types: [ labeled, unlabeled, opened, synchronize, reopened, ready_for_review, review_requested ]

jobs:
  auto-approve:
    uses: xivstats/workflows/.github/workflows/autoapprove.yml@main
