# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - run: npm install
      - run: npm test
      - run: npm run build
      - run: npm run lint

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm run build
      - run: git config --global user.email "automation@reidweb.com"
      - run: git config --global user.name "GitHub Actions"
      - run: git checkout -b release/${{ github.event.release.tag_name }}
      - run: git rev-parse --abbrev-ref HEAD
      - run: npm run release ${{ github.event.release.tag_name }}
      - name: Release new version to NPM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@xivstats'
      # Publish to GitHub Packages
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PUSH_TOKEN }}
          branch: 'release/${{ github.event.release.tag_name }}'
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: 'release/${{ github.event.release.tag_name }}'
          destination_branch: main
          pr_title: 'chore(release): ${{ github.event.release.tag_name }}'
          pr_body: 'Auto-compile changelog, increment package, then auto-merge changes made for v${{ github.event.release.tag_name }} into main'
          pr_label: 'pr/auto-approve'
          github_token: ${{ secrets.GH_PUSH_TOKEN }}
