# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    uses: xivstats/workflows/.github/workflows/ts-npm-build.yml@main
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  publish:
    needs: build
    uses: xivstats/workflows/.github/workflows/ts-npm-release.yml@main
    secrets:
      GH_PUSH_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
